// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.23.0";

// src/lib/mcp/tools/list-products.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z } from "npm:zod@^3.25.76";
import { PRODUKTY } from "npm:@/config/products";
var list_products_default = defineTool({
  name: "list_products",
  title: "List products",
  description: "Vr\xE1t\xED seznam v\u0161ech typ\u016F produkt\u016F (tri\u010Dko, mikina, d\u011Btsk\xE9, ta\u0161ka, pol\u0161t\xE1\u0159, z\xE1st\u011Bra) s jejich Upgates slugy.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => {
    const items = Object.entries(PRODUKTY).map(([key, cfg]) => ({
      key,
      slugy: cfg.slugy,
      pocet_zon: cfg.zony.length
    }));
    return {
      content: [{ type: "text", text: JSON.stringify(items, null, 2) }],
      structuredContent: { products: items }
    };
  }
});

// src/lib/mcp/tools/get-product-zones.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z2 } from "npm:zod@^3.25.76";
import { PRODUKTY as PRODUKTY2 } from "npm:@/config/products";
var get_product_zones_default = defineTool2({
  name: "get_product_zones",
  title: "Get product placement zones",
  description: "Vr\xE1t\xED konfiguraci um\xEDst\u011Bn\xED v\xFD\u0161ivky pro dan\xFD typ produktu \u2014 pozice, velikosti a kolize.",
  inputSchema: {
    product: z2.string().describe("Kl\xED\u010D produktu (tricko, mikina, detske, taska_velka, polstar, zastera) nebo Upgates slug.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ product }) => {
    const key = product.toLowerCase();
    let cfg = PRODUKTY2[key];
    if (!cfg) {
      const found = Object.values(PRODUKTY2).find((p) => p.slugy.includes(key));
      if (found) cfg = found;
    }
    if (!cfg) {
      return {
        content: [{ type: "text", text: `Produkt "${product}" nebyl nalezen. Dostupn\xE9: ${Object.keys(PRODUKTY2).join(", ")}` }],
        isError: true
      };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(cfg, null, 2) }],
      structuredContent: { product: cfg }
    };
  }
});

// src/lib/mcp/tools/get-pricing.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z3 } from "npm:zod@^3.25.76";
var get_pricing_default = defineTool3({
  name: "get_pricing",
  title: "Get embroidery pricing",
  description: "Vr\xE1t\xED cen\xEDk v\xFD\u0161ivek Alfie Store (p\u0159\xEDplatky za dal\u0161\xED v\xFD\u0161ivky).",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => {
    const pricing = {
      mena: "CZK",
      pravidla: [
        "Prvn\xED mal\xE1 v\xFD\u0161ivka (13\xD713 cm) je zahrnuta v cen\u011B produktu.",
        "Ka\u017Ed\xE1 dal\u0161\xED mal\xE1 v\xFD\u0161ivka nav\xEDc: +300 K\u010D",
        "Velk\xE1 v\xFD\u0161ivka (25\xD715 cm): +500 K\u010D"
      ],
      polozky: {
        mala_prvni: 0,
        mala_navic: 300,
        velka: 500
      }
    };
    return {
      content: [{ type: "text", text: JSON.stringify(pricing, null, 2) }],
      structuredContent: pricing
    };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "alfie-store-mcp",
  title: "Alfie Store konfigur\xE1tor",
  version: "0.1.0",
  instructions: "N\xE1stroje pro Alfie Store \u2014 e-shop s v\xFD\u0161ivkami d\u011Btsk\xFDch kreseb. Umo\u017E\u0148uje AI asistent\u016Fm \u010D\xEDst konfiguraci produkt\u016F, um\xEDst\u011Bn\xED v\xFD\u0161ivek a cen\xEDk.",
  tools: [list_products_default, get_product_zones_default, get_pricing_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.23.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
