// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.23.0";

// src/lib/mcp/tools/list-products.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z } from "npm:zod@^3.25.76";

// src/config/products.ts
var POSITIONS = {
  srdce: { x: 62, y: 38, scale: 18 },
  hrudnik: { x: 50, y: 45, scale: 35 },
  "lem-p": { x: 38, y: 75, scale: 18 },
  krk: { x: 50, y: 25, scale: 18 },
  zada: { x: 50, y: 45, scale: 40 },
  "lem-z": { x: 38, y: 75, scale: 18 },
  "hrudnik-v": { x: 50, y: 45, scale: 35 },
  predni: { x: 50, y: 45, scale: 35 },
  zadni: { x: 50, y: 45, scale: 35 },
  prirodni: { x: 50, y: 45, scale: 35 },
  barvena: { x: 50, y: 45, scale: 35 },
  mala: { x: 50, y: 45, scale: 22 },
  velka: { x: 50, y: 45, scale: 35 }
};
function pos(id) {
  const p = POSITIONS[id] || { x: 50, y: 45, scale: 25 };
  return { position: { x: p.x, y: p.y }, imageScale: p.scale };
}
var PRODUKTY = {
  tricko: {
    slugy: ["panske-tricko", "damske-tricko", "tricko"],
    zony: [
      { id: "srdce", nazev: "Vlevo u srdce", info: "13\xD713 cm \xB7 p\u0159edn\xED strana", typ: "mala", select: "V\xFD\u0161ivka (13x13 cm)", value: "Vlevo u srdce", barva: "#ff2600", predni: true, ...pos("srdce") },
      { id: "hrudnik", nazev: "Uprost\u0159ed hrudn\xEDku", info: "25\xD715 cm \xB7 p\u0159edn\xED strana", typ: "velka", select: "Velk\xE1 v\xFD\u0161ivka (25x15 cm)", value: "Uprost\u0159ed hrudn\xEDku", barva: "#1D9E75", predni: true, ...pos("hrudnik") },
      { id: "lem-p", nazev: "Vpravo dole \xB7 p\u0159edn\xED lem", info: "13\xD713 cm \xB7 p\u0159edn\xED strana", typ: "navic", select: "V\xFD\u0161ivka nav\xEDc (13x13 cm)", value: "Vpravo dole u p\u0159edn\xEDho lemu", barva: "#7F77DD", predni: true, ...pos("lem-p") },
      { id: "krk", nazev: "Za krkem", info: "13\xD713 cm \xB7 zadn\xED strana", typ: "navic", select: "V\xFD\u0161ivka nav\xEDc (13x13 cm)", value: "Za krkem", barva: "#BA7517", predni: false, ...pos("krk") },
      { id: "zada", nazev: "Uprost\u0159ed zad", info: "25\xD715 cm \xB7 zadn\xED strana", typ: "velka", select: "Velk\xE1 v\xFD\u0161ivka (25x15 cm)", value: "Uprost\u0159ed zad", barva: "#1D9E75", predni: false, ...pos("zada") },
      { id: "lem-z", nazev: "Vpravo dole \xB7 zadn\xED lem", info: "13\xD713 cm \xB7 zadn\xED strana", typ: "navic", select: "V\xFD\u0161ivka nav\xEDc (13x13 cm)", value: "Vpravo dole u zadn\xEDho lemu", barva: "#7F77DD", predni: false, ...pos("lem-z") }
    ],
    kolize: [["srdce", "hrudnik"]]
  },
  mikina: {
    slugy: ["mikina", "panska-mikina", "damska-mikina"],
    zony: [
      { id: "srdce", nazev: "Vlevo u srdce", info: "13\xD713 cm \xB7 p\u0159edn\xED strana", typ: "mala", select: "V\xFD\u0161ivka (13x13 cm)", value: "Vlevo u srdce", barva: "#ff2600", predni: true, ...pos("srdce") },
      { id: "hrudnik", nazev: "Uprost\u0159ed hrudn\xEDku", info: "25\xD715 cm \xB7 p\u0159edn\xED strana", typ: "velka", select: "Velk\xE1 v\xFD\u0161ivka (25x15 cm)", value: "Uprost\u0159ed hrudn\xEDku", barva: "#1D9E75", predni: true, ...pos("hrudnik") },
      { id: "krk", nazev: "Za krkem", info: "13\xD713 cm \xB7 zadn\xED strana", typ: "navic", select: "V\xFD\u0161ivka nav\xEDc (13x13 cm)", value: "Za krkem", barva: "#BA7517", predni: false, ...pos("krk") },
      { id: "zada", nazev: "Uprost\u0159ed zad", info: "25\xD715 cm \xB7 zadn\xED strana", typ: "velka", select: "Velk\xE1 v\xFD\u0161ivka (25x15 cm)", value: "Uprost\u0159ed zad", barva: "#1D9E75", predni: false, ...pos("zada") },
      { id: "lem-z", nazev: "Vpravo dole \xB7 zadn\xED lem", info: "13\xD713 cm \xB7 zadn\xED strana", typ: "navic", select: "V\xFD\u0161ivka nav\xEDc (13x13 cm)", value: "Vpravo dole u zadn\xEDho lemu", barva: "#7F77DD", predni: false, ...pos("lem-z") }
    ],
    kolize: [["srdce", "hrudnik"]]
  },
  detske: {
    slugy: ["detske", "detska-mikina", "detske-tricko"],
    zony: [
      { id: "hrudnik", nazev: "Uprost\u0159ed hrudn\xEDku", info: "13\xD713 cm \xB7 p\u0159edn\xED strana", typ: "mala", select: "V\xFD\u0161ivka (13x13 cm)", value: "Uprost\u0159ed hrudn\xEDku", barva: "#ff2600", predni: true, ...pos("hrudnik") },
      { id: "lem-p", nazev: "Vpravo dole \xB7 p\u0159edn\xED lem", info: "13\xD713 cm \xB7 p\u0159edn\xED strana", typ: "navic", select: "V\xFD\u0161ivka nav\xEDc (13x13 cm)", value: "Vpravo dole u p\u0159edn\xEDho lemu", barva: "#7F77DD", predni: true, ...pos("lem-p") },
      { id: "hrudnik-v", nazev: "Uprost\u0159ed hrudn\xEDku (velk\xE1)", info: "25\xD715 cm \xB7 p\u0159edn\xED strana", typ: "velka", select: "Velk\xE1 v\xFD\u0161ivka (25x15 cm)", value: "Uprost\u0159ed hrudn\xEDku", barva: "#1D9E75", predni: true, ...pos("hrudnik-v") },
      { id: "krk", nazev: "Za krkem", info: "13\xD713 cm \xB7 zadn\xED strana", typ: "navic", select: "V\xFD\u0161ivka nav\xEDc (13x13 cm)", value: "Za krkem", barva: "#BA7517", predni: false, ...pos("krk") },
      { id: "zada", nazev: "Uprost\u0159ed zad", info: "25\xD715 cm \xB7 zadn\xED strana", typ: "velka", select: "Velk\xE1 v\xFD\u0161ivka (25x15 cm)", value: "Uprost\u0159ed zad", barva: "#1D9E75", predni: false, ...pos("zada") },
      { id: "lem-z", nazev: "Vpravo dole \xB7 zadn\xED lem", info: "13\xD713 cm \xB7 zadn\xED strana", typ: "navic", select: "V\xFD\u0161ivka nav\xEDc (13x13 cm)", value: "Vpravo dole u zadn\xEDho lemu", barva: "#7F77DD", predni: false, ...pos("lem-z") }
    ],
    kolize: [["hrudnik", "hrudnik-v"]]
  },
  taska_velka: {
    slugy: ["platena-taska", "taska-s-vysivkou"],
    zony: [
      { id: "predni", nazev: "P\u0159edn\xED strana", info: "20\xD720 cm", typ: "mala", select: "V\xFD\u0161ivka (13x13 cm)", value: "Vlevo u srdce", barva: "#ff2600", predni: true, ...pos("predni") },
      { id: "zadni", nazev: "Zadn\xED strana", info: "20\xD720 cm", typ: "navic", select: "V\xFD\u0161ivka nav\xEDc (13x13 cm)", value: "Vpravo dole u zadn\xEDho lemu", barva: "#1D9E75", predni: false, ...pos("zadni") }
    ],
    kolize: []
  },
  polstar: {
    slugy: ["polstar", "povlak-na-polstar"],
    zony: [
      { id: "prirodni", nazev: "P\u0159\xEDrodn\xED strana", info: "20\xD720 cm", typ: "mala", select: "V\xFD\u0161ivka pol\u0161t\xE1\u0159e", value: "P\u0159\xEDrodn\xED strana", barva: "#ff2600", predni: true, ...pos("prirodni") },
      { id: "barvena", nazev: "Barevn\xE1 strana", info: "20\xD720 cm", typ: "navic", select: "V\xFD\u0161ivka pol\u0161t\xE1\u0159e", value: "Barevn\xE1 strana", barva: "#1D9E75", predni: false, ...pos("barvena") }
    ],
    kolize: []
  },
  zastera: {
    slugy: ["zastera"],
    zony: [
      { id: "mala", nazev: "Mal\xE1 v\xFD\u0161ivka", info: "13\xD713 cm \xB7 p\u0159edn\xED strana", typ: "mala", select: "Velikost v\xFD\u0161ivky na z\xE1st\u011Bru", value: "Mal\xE1 v\xFD\u0161ivka (13x13 cm)", barva: "#ff2600", predni: true, ...pos("mala") },
      { id: "velka", nazev: "Velk\xE1 v\xFD\u0161ivka", info: "25\xD715 cm \xB7 p\u0159edn\xED strana", typ: "velka", select: "Velikost v\xFD\u0161ivky na z\xE1st\u011Bru", value: "Velk\xE1 v\xFD\u0161ivka (25x15 cm) (+500 K\u010D)", barva: "#1D9E75", predni: true, ...pos("velka") }
    ],
    kolize: [["mala", "velka"]]
  }
};

// src/lib/mcp/tools/list-products.ts
var list_products_default = defineTool({
  name: "list_products",
  title: "List products",
  description: "Vr\xE1t\xED seznam v\u0161ech typ\u016F produkt\u016F (tri\u010Dko, mikina, d\u011Btsk\xE9, ta\u0161ka, pol\u0161t\xE1\u0159, z\xE1st\u011Bra) s jejich Upgates slugy.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => {
    const items = Object.entries(PRODUKTY).map(([key, cfg]) => ({
      key,
      slugy: cfg.slugy,
      pocet_zon: cfg.zony.length
    }));
    return {
      content: [{ type: "text", text: JSON.stringify(items, null, 2) }],
      structuredContent: { products: items }
    };
  }
});

// src/lib/mcp/tools/get-product-zones.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z2 } from "npm:zod@^3.25.76";
var get_product_zones_default = defineTool2({
  name: "get_product_zones",
  title: "Get product placement zones",
  description: "Vr\xE1t\xED konfiguraci um\xEDst\u011Bn\xED v\xFD\u0161ivky pro dan\xFD typ produktu \u2014 pozice, velikosti a kolize.",
  inputSchema: {
    product: z2.string().describe("Kl\xED\u010D produktu (tricko, mikina, detske, taska_velka, polstar, zastera) nebo Upgates slug.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ product }) => {
    const key = product.toLowerCase();
    let cfg = PRODUKTY[key];
    if (!cfg) {
      const found = Object.values(PRODUKTY).find((p) => p.slugy.includes(key));
      if (found) cfg = found;
    }
    if (!cfg) {
      return {
        content: [{ type: "text", text: `Produkt "${product}" nebyl nalezen. Dostupn\xE9: ${Object.keys(PRODUKTY).join(", ")}` }],
        isError: true
      };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(cfg, null, 2) }],
      structuredContent: { product: cfg }
    };
  }
});

// src/lib/mcp/tools/get-pricing.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z3 } from "npm:zod@^3.25.76";
var get_pricing_default = defineTool3({
  name: "get_pricing",
  title: "Get embroidery pricing",
  description: "Vr\xE1t\xED cen\xEDk v\xFD\u0161ivek Alfie Store (p\u0159\xEDplatky za dal\u0161\xED v\xFD\u0161ivky).",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => {
    const pricing = {
      mena: "CZK",
      pravidla: [
        "Prvn\xED mal\xE1 v\xFD\u0161ivka (13\xD713 cm) je zahrnuta v cen\u011B produktu.",
        "Ka\u017Ed\xE1 dal\u0161\xED mal\xE1 v\xFD\u0161ivka nav\xEDc: +300 K\u010D",
        "Velk\xE1 v\xFD\u0161ivka (25\xD715 cm): +500 K\u010D"
      ],
      polozky: {
        mala_prvni: 0,
        mala_navic: 300,
        velka: 500
      }
    };
    return {
      content: [{ type: "text", text: JSON.stringify(pricing, null, 2) }],
      structuredContent: pricing
    };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "alfie-store-mcp",
  title: "Alfie Store konfigur\xE1tor",
  version: "0.1.0",
  instructions: "N\xE1stroje pro Alfie Store \u2014 e-shop s v\xFD\u0161ivkami d\u011Btsk\xFDch kreseb. Umo\u017E\u0148uje AI asistent\u016Fm \u010D\xEDst konfiguraci produkt\u016F, um\xEDst\u011Bn\xED v\xFD\u0161ivek a cen\xEDk.",
  tools: [list_products_default, get_product_zones_default, get_pricing_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.23.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
